typography_spectrum: 0.29475143179297447
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.21995009598322213
  lightness: 0.6026378951501101
  saturation: 0.4904960482381284
  rhythmicContrast: 0.7685438683256507
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2905413266271353
analytics:
  google: null
  facebook: null
  twitter: null
name: Raleigh Lee Realty
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: 98349251-6e12-40f1-ae7b-990d18e3482e
    type: content
favicon: null
title: Metro Atlanta Residential Real Estate
description: Energy | Integrity | Mastery
purpose: []
