name: Raleigh R. Lee and Associates
favicon: null
layout_spectrum: 0.2897107247263193
typography_spectrum: 0.8267767529468983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5935790091753006
  lightness: 0.4783893737476319
  saturation: 0.5721109793521464
  rhythmicContrast: 0.07609366648830473
purpose: []
