name: 'Raleigh R. Lee & Associates'
favicon: null
layout_spectrum: 0.2897107247263193
typography_spectrum: 0.8267767529468983
title: 'Raleigh R. Lee & Associates'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#028aed'
    - '#efefef'
    - '#170f0d'
    - '#a47c49'
    - '#d1ab64'
  brandStrength: 0.5935790091753006
  lightness: 0.4783893737476319
  saturation: 0.5721109793521464
  rhythmicContrast: 0.07609366648830473
purpose: []
